services:
  suomi-fi-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: suomi-fi-keycloak
    command: start-dev --http-port 8081 --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    volumes:
      - ./suomi-fi-realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      keycloak-network:
        aliases:
          - suomi-fi-keycloak.localhost

  main-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: main-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./main-realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      keycloak-network:
        aliases:
          - main-keycloak.localhost

networks:
  keycloak-network:
    driver: bridge
